### ISSUE TITLE
32-bit platform assumed by clz implementations

### ISSUE THREAD

**Issue by tomalakgeretkal** [orlp/libop#1]
For GNU, `__builtin_clzll` is used for `uint64_t` _clz_ and `__builtin_clzl` is used for `uint32_t`.

But I have a x86_64 platform on which `unsigned long` is 64-bit (derp) so `clz(uint32_t)` gives me the wrong results (and I'm guessing `clz(uint64_t)` would, too).

Is there an easy fix for this? It's a shame GNU doesn't seem to have any fixed-width _clz_ intrinsic....

**Comment by orlp** [comment]
There is an easy fix, by using `__builtin_clz` for `uint32_t` and `__builtin_clzll` for `uint64_t`, this assumes `unsigned` is 32-bit and `unsigned long long` is 64-bit, which is a reasonable assumption.

Let me fix that right now.

P.S.: I didn't know my library had any real users other than myself :)

**Comment by tomalakgeretkal** [comment]
That's exactly what I've done for my i686 and x86_64 platforms as it happens to work. But I was hoping for an easy fix for the lack of portability ;)

And yeah I use this in commercial software (with the relevant licence requirements intact, of course!). I think I briefly mentioned this to you months ago :)

**Comment by orlp** [comment]
Allrighty, closing this.

**Comment by orlp** [comment]
@tomalakgeretkal If you want to you can do a `static_assert(sizeof(unsigned) * CHAR_BIT == 32 && sizeof(unsigned long long) * CHAR_BIT == 64)` to make sure your assumption holds and fail the build if it doesn't.
